version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
      time: "01:30"
      timezone: "America/New_York"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:30"
      timezone: "America/New_York"
    pull-request-branch-name:
      separator: "-"
