version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
      time: "01:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
