name: terraform

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/terraform.yml'
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    strategy:
      matrix:
        working_directory: [terraform/random, terraform/time]

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.working_directory }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.1.0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.actor != 'dependabot[bot]'
        run: terraform apply -parallelism=50 -auto-approve tfplan
